# devicetree.tcl - Generate device tree from .xsa for Red Pitaya 4-channel
# Usage from root folder:
#   xsct source/scripts/devicetree.tcl led_blinker_4ch ps7_cortexa9_0
#
# Input: project/led_blinker_4ch.xsa (generated by hwdef.tcl)
# Output: project/devicetree/system-top.dts and system-top.dtb

set project_name [lindex $argv 0]
set proc_name    ps7_cortexa9_0

# Paths (relative to root /home/nay/FPGA/LED)
set xsa_file     "project/${project_name}.xsa"
set output_dir   "project/devicetree"

# Create output directory
file mkdir $output_dir

# Temporary hardware directory (needed by HSI)
set hard_dir "project/${project_name}.hard"
file mkdir $hard_dir
file copy -force $xsa_file $hard_dir/${project_name}.xsa

# Open hardware design
hsi open_hw_design $hard_dir/${project_name}.xsa

hsi set_repo_path tmp/device-tree-xlnx-xilinx_v2025.1

# Create device tree domain
hsi create_sw_design devicetree -proc $proc_name -os device_tree 

# Generate device tree files into our clean directory
hsi generate_target -dir $output_dir

# Close everything
hsi close_sw_design [hsi current_sw_design]
hsi close_hw_design [hsi current_hw_design]

# Clean up temporary hard directory
file delete -force $hard_dir